[project]
    name = "bedrock-fsb-extracter"
    version = "0.0.0"
    description = "Add your description here"
    readme = "README.md"
    requires-python = ">=3.8"
    dependencies = [
    "sfyi-fsb5>=1.1",
]
