[project]
name = "MineUtaU"
version = "0.0.1"
description = "一个针对 Minecraft 原版音效包的类人力 Vocaloid 语音/歌声合成工具。 "
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
members = [
    "tools/bedrock_fsb_extracter",
]
